# Generated by Django 2.2.24 on 2021-08-12 09:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models

import mozilla_django_oidc_db.models


class Migration(migrations.Migration):

    dependencies = [
        ("mozilla_django_oidc_db", "0003_auto_20210719_0803"),
    ]

    operations = [
        migrations.AddField(
            model_name="openidconnectconfig",
            name="claim_mapping",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=mozilla_django_oidc_db.models.get_claim_mapping,
                help_text="Mapping from user-model fields to ADFS claims",
                verbose_name="claim mapping",
            ),
        ),
        migrations.AddField(
            model_name="openidconnectconfig",
            name="sync_groups",
            field=models.BooleanField(
                default=True,
                help_text="Synchronize the local user groups with the provided groups. Note that this means a user is removed from all groups if there is no group claim. Uncheck to manage groups manually.",
                verbose_name="synchronize groups?",
            ),
        ),
    ]
