# Generated by Django 4.2.20 on 2025-04-11 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mozilla_django_oidc_db", "0007_migrate_oidc_data"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OpenIDConnectConfig",
        ),
    ]
