# Generated by Django 5.2.11 on 2026-03-13 16:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mozilla_django_oidc_db", "0008_delete_openidconnectconfig"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OpenIDConnectConfig",
        ),
    ]
