# Generated by Django 5.0.2 on 2024-07-02 07:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0002_emptyconfig_oidc_keycloak_idp_hint_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emptyconfig",
            name="oidc_exempt_urls",
        ),
    ]
