# Generated by Django 4.2.20 on 2025-05-08 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0004_anotheremptyconfig"),
        ("mozilla_django_oidc_db", "0008_delete_openidconnectconfig"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AnotherEmptyConfig",
        ),
        migrations.DeleteModel(
            name="EmptyConfig",
        ),
        migrations.DeleteModel(
            name="WrongConfigModel",
        ),
        migrations.DeleteModel(
            name="CustomCallbackViewConfig",
        ),
    ]
