# Generated by Django 4.2.20 on 2025-04-14 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0004_anotheremptyconfig"),
        ("mozilla_django_oidc_db", "0009_openidconnectconfig_legacy"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmptyConfig",
        ),
        migrations.DeleteModel(
            name="WrongConfigModel",
        ),
        migrations.DeleteModel(
            name="CustomCallbackViewConfig",
        ),
    ]
