# Generated by Django 4.2.20 on 2025-05-06 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0005_delete_emptyconfig_delete_wrongconfigmodel_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AnotherEmptyConfig",
        ),
    ]
